-- update table과 table을 합치는 샘플 쿼리
SELECT IDX, NAME, BIRTH, CITY, GENDER, JOIN_DT, MAIL, LOGIN_IP, STATUS FROM TEST_MEMBER_UPDATED
WHERE SEQ IN (SELECT MAX(SEQ) FROM TEST_MEMBER_UPDATED WHERE STATUS IN ('STATUS_APPROVED', 'STATUS_PENDING') GROUP BY IDX )
UNION
SELECT IDX, NAME, BIRTH, CITY, GENDER, JOIN_DT, MAIL, LOGIN_IP, NULL FROM TEST_MEMBER WHERE IDX NOT IN (
    SELECT IDX FROM TEST_MEMBER_UPDATED
    WHERE SEQ IN (SELECT MAX(SEQ) FROM TEST_MEMBER_UPDATED WHERE STATUS IN ('STATUS_APPROVED', 'STATUS_PENDING') GROUP BY IDX )
)
ORDER BY IDX;
