DROP TABLE IF EXISTS GSCN.GSCN_TRTM_OPRT;
DROP TABLE IF EXISTS GSCN.GSCN_TRTM_OPRT_UPDATED;

CREATE TABLE IF NOT EXISTS GSCN.GSCN_TRTM_OPRT (
    hosp_cd                    varchar(20) not null,
    pt_no                      varchar(10) not null,
    oprt_ymd                   timestamp   not null,
    oprt_seq                   numeric(3)  not null,
    oprt_kncd                  varchar(20),
    oprt_knnm                  varchar(200),
    oprt_cd                    varchar(20),
    oprt_nm                    varchar(200),
    oprt_edi_cd                varchar(20),
    oprt_edi_nm                varchar(200),
    oprt_smct_cd               varchar(200),
    oprt_smct_nm               varchar(1000),
    oprt_icd9cm_cd             varchar(20),
    oprt_icd9cm_nm             varchar(1000),
    oprt_ldtm                  varchar(20),
    oprt_prps_cd               varchar(20),
    oprt_prps_nm               varchar(200),
    oprt_mtcd                  varchar(20),
    oprt_mtnm                  varchar(200),
    oprt_anst_site_cd          varchar(20),
    oprt_anst_site_nm          varchar(200),
    asa_scor_cd                varchar(20),
    asa_scor_nm                varchar(200),
    oprt_incs_mtcd             varchar(20),
    oprt_incs_mtnm             varchar(200),
    oprt_crmr_tumr_loca_cd     varchar(20),
    oprt_crmr_tumr_loca_nm     varchar(200),
    oprt_lngt_1_tumr_loca_cd   varchar(20),
    oprt_lngt_1_tumr_loca_nm   varchar(200),
    oprt_lngt_2_tumr_loca_cd   varchar(20),
    oprt_lngt_2_tumr_loca_nm   varchar(200),
    diag_lpex_yn_unid_spcd     varchar(20),
    diag_lpex_yn_unid_spnm     varchar(50),
    oprm_ensp_use_yn_unid_spcd varchar(20),
    oprm_ensp_use_yn_unid_spnm varchar(50),
    flrn_imag_use_yn_unid_spcd varchar(20),
    flrn_imag_use_yn_unid_spnm varchar(50),
    inop_antp_cd               varchar(20),
    inop_antp_nm               varchar(200),
    adh_ibtr_use_yn_unid_spcd  varchar(20),
    adh_ibtr_use_yn_unid_spnm  varchar(50),
    adh_ibtr_gods_nm           varchar(200),
    omnl_srmv_rang_cd          varchar(20),
    omnl_srmv_rang_nm          varchar(200),
    curdg_cd                   varchar(20),
    curdg_nm                   varchar(200),
    ln_srmv_dgre_cd            varchar(20),
    ln_srmv_dgre_nm            varchar(200),
    ln_srmv_dgre_detl_cont     varchar(500),
    mrge_srmv_site_cd          varchar(20),
    mrge_srmv_site_nm          varchar(200),
    repr_kncd                  varchar(20),
    repr_knnm                  varchar(200),
    repr_use_dvce_nm           varchar(200),
    repr_mtcd                  varchar(20),
    repr_mtnm                  varchar(200),
    repr_aprmthd_cd            varchar(20),
    repr_aprmthd_nm            varchar(200),
    oprt_ebl_qty               numeric(5),
    asct_yn_unid_spcd          varchar(20),
    asct_yn_unid_spnm          varchar(50),
    crtn_dt                    timestamp   not null,
    idx                        varchar(100),
    pact_id                    varchar(50),
    procedure_cnte             varchar(4000),
    comments                   varchar(4000),
    SORT_SEQ NUMERIC(10,0) null, 			-- UI용 정렬용
    free_text varchar(1000) null, 			-- UI용 검색용
    constraint gscn_trtm_oprt_pk
    primary key (hosp_cd, pt_no, oprt_ymd, oprt_seq)
);
