CREATE SCHEMA IF NOT EXISTS GSCN;

create table if not exists gscn.cncr_rgst
(
    hosp_cd        varchar(4)   not null,
    pt_no          varchar(15)  not null,
    fdx            varchar(8),
    brth           varchar(6),
    age            varchar(3),
    sex            varchar(20),
    popcode        varchar(20),
    popname        varchar(50),
    frgcode        varchar(20),
    frgname        varchar(50),
    hmlscode       varchar(20),
    hmlsname       varchar(50),
    jobcode        varchar(20),
    jobname        varchar(50),
    job1           varchar(50),
    unknownjob     varchar(50),
    visitpathcode  varchar(20),
    visitpathname  varchar(50),
    visitpath_desc varchar(50),
    tcode          varchar(20),
    tcode1         varchar(50),
    tcode2         varchar(50),
    latercode      varchar(20),
    latername      varchar(100),
    mcode          varchar(20),
    mcode1         varchar(50),
    mcode2         varchar(50),
    bunhwadocode   varchar(20),
    bunhwadoname   varchar(50),
    expire         timestamp,
    sain           varchar(20),
    methodcode     varchar(20),
    methodname     varchar(100),
    method2        varchar(50),
    methodetc      varchar(50),
    txcheckcode    varchar(20),
    txcheckname    varchar(50),
    tx             varchar(20),
    txetc          varchar(50),
    recoyear       varchar(50),
    admisdate      timestamp,
    disdate        timestamp,
    dbyear         varchar(4),
    inputday       timestamp,
    seeryear       varchar(4),
    seercode       varchar(20),
    seername       varchar(100),
    stagecode      varchar(20),
    stageyear      varchar(4),
    stagedesc      varchar(50),
    metacode1      varchar(20),
    metacode2      varchar(20),
    metacode3      varchar(20),
    crtn_dt        timestamp    not null,
    gid            varchar(10),
    idx            varchar(100) not null,
    pt_nm          varchar(50),
    pt_brdy_dt     varchar(50),
    comments       varchar(4000),
    status         varchar(50),
    sain_cnte      varchar(1000),
    sort_seq       numeric(4),
    constraint cncr_rgst_pk
    primary key (hosp_cd, pt_no, idx)
    );

create table if not exists gscn.cncr_rgst_updated
(
    hosp_cd            varchar(4)   not null,
    pt_no              varchar(15)  not null,
    fdx                varchar(8),
    brth               varchar(6),
    age                varchar(3),
    sex                varchar(20),
    popcode            varchar(20),
    popname            varchar(50),
    frgcode            varchar(20),
    frgname            varchar(50),
    hmlscode           varchar(20),
    hmlsname           varchar(50),
    jobcode            varchar(20),
    jobname            varchar(50),
    job1               varchar(50),
    unknownjob         varchar(50),
    visitpathcode      varchar(20),
    visitpathname      varchar(50),
    visitpath_desc     varchar(50),
    tcode              varchar(20),
    tcode1             varchar(50),
    tcode2             varchar(50),
    latercode          varchar(20),
    latername          varchar(100),
    mcode              varchar(20),
    mcode1             varchar(50),
    mcode2             varchar(50),
    bunhwadocode       varchar(20),
    bunhwadoname       varchar(50),
    expire             timestamp,
    sain               varchar(20),
    methodcode         varchar(20),
    methodname         varchar(100),
    method2            varchar(50),
    methodetc          varchar(50),
    txcheckcode        varchar(20),
    txcheckname        varchar(50),
    tx                 varchar(20),
    txetc              varchar(50),
    recoyear           varchar(50),
    admisdate          timestamp,
    disdate            timestamp,
    dbyear             varchar(4),
    inputday           timestamp,
    seeryear           varchar(4),
    seercode           varchar(20),
    seername           varchar(100),
    stagecode          varchar(20),
    stageyear          varchar(4),
    stagedesc          varchar(50),
    metacode1          varchar(20),
    metacode2          varchar(20),
    metacode3          varchar(20),
    crtn_dt            timestamp,
    gid                varchar(10),
    idx                varchar(100) not null,
    pt_nm              varchar(50),
    pt_brdy_dt         varchar(50),
    comments           varchar(4000),
    created_by         varchar(50),
    created_date       timestamp,
    last_modified_by   varchar(50),
    last_modified_date timestamp,
    status             varchar(50),
    sain_cnte          varchar(1000),
    sort_seq           numeric(4),
    constraint cncr_rgst_updated_pk
    primary key (hosp_cd, pt_no, idx)
    );
